### ISSUE TITLE
Warnings and Fontawesome old version

### ISSUE THREAD

**Issue by MyracleDesign** [SpellCraft/mdb4-boilerplate#3]
I checked this repo and seen that it is a bit out of date. I made a fork and updated a bit maybe you can have a glance, and we can maybe merge it.

https://github.com/MyracleDesign/mdb4-boilerplate

**Comment by SpellCraft** [comment]
Indeed. I've been working on a huge update to the repository the past 2 months to reflect some changes in Webpack, MDB with bug fixes, minification and a few other things, though because of a head injury and surgery I've been unable to do much the last 3-4 weeks.

Thanks for taking the time to update the repository on your own. :) I'll let you know when I'm pushing an update to the repo.
